version: "3.9"
services:
  db:
    image: postgres:9.6
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data
    restart: always
  app:
    build:
      context: .
      args:
        B_UID: "${UID}"
        B_GID: "${GID}"
        RAILS_PORT: "${RAILS_PORT}"
    env_file:
      - .env
      - app.env
    ports:
      - "${RAILS_PORT}:${RAILS_PORT}"
      - 1234:1234
    depends_on:
      - db
      - redis
    volumes:
      - codebase:/app
  redis:
    image: redis:6.2.6-alpine3.15
    restart: on-failure
    command: --port ${REDIS_PORT}
    ports:
      - ${REDIS_PORT}:${REDIS_PORT}
    volumes:
      - redisdb:/data
volumes:
  db:
  redisdb:
  codebase:

x-mutagen:
  sync:
    codebase:
      alpha: '.'
      beta: 'volume://codebase'
      configurationBeta:
        permissions:
          defaultOwner: "id:${UID}"
          defaultGroup: "id:${GID}"

