default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV.fetch("POSTGRES_USER", "postgresql") %>
  password: <%= ENV.fetch("POSTGRES_PASSWORD", "postgresql") %>
  host: <%= ENV.fetch("DB_HOST", "localhost") %>
  port: <%= ENV.fetch("DB_PORT", 5432) %>


development:
  <<: *default
  database: <%= ENV.fetch("POSTGRES_DB", "development") %>

test:
  adapter: sqlite3
  database: db/test.sqlite3
  pool: 5
  timeout: 5000

production:
  <<: *default
  database: <%= ENV.fetch("POSTGRES_DB", "production") %>